"""Creación relación entre  auth_users y roles

Revision ID: 00b1af32ec9d
Revises: d09c6e79634d
Create Date: 2024-05-26 16:38:38.474979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b1af32ec9d'
down_revision: Union[str, None] = 'd09c6e79634d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'auth_users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_users', type_='foreignkey')
    op.drop_column('auth_users', 'role_id')
    # ### end Alembic commands ###
