"""3

Revision ID: 0d3fe044b567
Revises: 00b1af32ec9d
Create Date: 2024-05-26 16:43:37.789960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0d3fe044b567'
down_revision: Union[str, None] = '00b1af32ec9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('password', table_name='auth_users')
    op.drop_column('auth_users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('password', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('password', 'auth_users', ['password'], unique=True)
    # ### end Alembic commands ###
