"""add column total price in reservation

Revision ID: 35891536fa9e
Revises: b23a5747000a
Create Date: 2024-06-06 23:14:25.027698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35891536fa9e'
down_revision: Union[str, None] = 'b23a5747000a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('total_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'total_price')
    # ### end Alembic commands ###
