"""add_column_expiry_date

Revision ID: 7a78d4aa4f6d
Revises: 045b35a762e8
Create Date: 2024-06-05 19:16:17.874208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a78d4aa4f6d'
down_revision: Union[str, None] = '045b35a762e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_cards', sa.Column('expiry_date', sa.VARCHAR(length=5), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_cards', 'expiry_date')
    # ### end Alembic commands ###
