"""add columns price car and price moto in blueZone

Revision ID: 8ee50cf5175a
Revises: 35891536fa9e
Create Date: 2024-06-07 00:21:28.686697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee50cf5175a'
down_revision: Union[str, None] = '35891536fa9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blue_zones', sa.Column('price_car', sa.Float(), nullable=True))
    op.add_column('blue_zones', sa.Column('price_moto', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blue_zones', 'price_moto')
    op.drop_column('blue_zones', 'price_car')
    # ### end Alembic commands ###
