"""agregar campo observacion a la zona azul

Revision ID: a2f37edc116a
Revises: ca5e42d77d15
Create Date: 2024-06-05 23:38:11.777486

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a2f37edc116a"
down_revision: Union[str, None] = "ca5e42d77d15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blue_zones", sa.Column("observation", sa.String(length=500), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blue_zones", "observation")
    # ### end Alembic commands ###
