"""add_column expiry date

Revision ID: b23a5747000a
Revises: a2f37edc116a
Create Date: 2024-06-06 19:40:40.760129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23a5747000a'
down_revision: Union[str, None] = 'a2f37edc116a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_cards', sa.Column('expiry_date', sa.VARCHAR(length=5), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_cards', 'expiry_date')
    # ### end Alembic commands ###
