"""creacion tabla rating

Revision ID: ca5e42d77d15
Revises: 045b35a762e8
Create Date: 2024-06-05 21:38:12.734036

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "ca5e42d77d15"
down_revision: Union[str, None] = "045b35a762e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ratings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("qualification", sa.Integer(), nullable=False),
        sa.Column("observation", sa.String(length=2000), nullable=False),
        sa.Column("blue_zone_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["blue_zone_id"], ["blue_zones.id"], name="fk_rating_blue_zone_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("blue_zones", "observation")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blue_zones", sa.Column("observation", mysql.VARCHAR(length=200), nullable=True)
    )
    op.drop_table("ratings")
    # ### end Alembic commands ###
