"""Versión 1 base de datos

Revision ID: f8acaf3827ee
Revises: 
Create Date: 2024-06-02 15:45:56.167963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8acaf3827ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('place_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('names', sa.VARCHAR(length=255), nullable=False),
    sa.Column('last_names', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=255), nullable=True),
    sa.Column('document', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document')
    )
    op.create_table('auth_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_auth_user_role_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_auth_user_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('blue_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('address', sa.VARCHAR(length=100), nullable=False),
    sa.Column('observation', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('total_car_places', sa.Integer(), nullable=False),
    sa.Column('total_moto_places', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name='fk_blue_zones_area_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('credit_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.VARCHAR(length=255), nullable=False),
    sa.Column('titular_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('cvc', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_credit_cards_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('role_menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], name='fk_role_menus_menu_id'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_role_menus_role_id'),
    sa.PrimaryKeyConstraint('id', 'role_id', 'menu_id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('finish_date', sa.DateTime(), nullable=False),
    sa.Column('plate', sa.VARCHAR(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('place_type_id', sa.Integer(), nullable=False),
    sa.Column('blue_zone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blue_zone_id'], ['blue_zones.id'], name='fk_reservations_blue_zone_id'),
    sa.ForeignKeyConstraint(['place_type_id'], ['place_types.id'], name='fk_reservations_place_type_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_reservations_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    op.drop_table('role_menus')
    op.drop_table('credit_cards')
    op.drop_table('blue_zones')
    op.drop_table('auth_users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('place_types')
    op.drop_table('menus')
    op.drop_table('areas')
    # ### end Alembic commands ###
